name: 热榜自动推送墨水屏

on:
  schedule:
    - cron: "*/10 * * * *"  # 每 10 分钟运行一次
  workflow_dispatch:        # 允许手动运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install pillow requests schedule

      - name: 运行推送程序
        env:
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python dyhot.py
